name: Deploy to GCP Dev

on:
  push:
    branches:
      - main
    paths:
      - 'infra/environments/dev/**'
      - '.github/workflows/deploy-dev.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Dev Infra to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (OIDC)
        id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/720149050668/locations/global/workloadIdentityPools/github/providers/github-provider'
          service_account: 'grc-dev-invoker@cycorgi-grc-platform.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: infra/environments/dev
        run: terraform init -upgrade

      - name: Terraform Apply
        working-directory: infra/environments/dev
        run: terraform apply -auto-approve
