name: Deploy GRC Platform (Dev)

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: terraform-deployer@cycorgi-grc-platform.iam.gserviceaccount.com

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
